
/* File generated by gen_cfile.py. Should not be modified. */

#include "mbed_slave.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 Read_Inputs_8_Bit[] =		/* Mapped at index 0x6000, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 Polarity_Input_8_Bit[] =		/* Mapped at index 0x6002, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 Filter_Constant_Input_8_Bit[] =		/* Mapped at index 0x6003, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 Global_Interrupt_Enable_Digital = 0x0;		/* Mapped at index 0x6005, subindex 0x00 */
UNS8 Interrupt_Mask_Any_Change_8_Bit[] =		/* Mapped at index 0x6006, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 Interrupt_Mask_Low_to_High_8_Bit[] =		/* Mapped at index 0x6007, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 Interrupt_Mask_High_to_Low_8_Bit[] =		/* Mapped at index 0x6008, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 Write_Outputs_8_Bit[] =		/* Mapped at index 0x6200, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 Change_Polarity_Outputs_8_Bit[] =		/* Mapped at index 0x6202, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 Error_Mode_Outputs_8_Bit[] =		/* Mapped at index 0x6206, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };
UNS8 Error_Value_Outputs_8_Bit[] =		/* Mapped at index 0x6207, subindex 0x01 - 0x01 */
  {
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 mbed_slave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 mbed_slave_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 mbed_slave_iam_a_slave = 1;

TIMER_HANDLE mbed_slave_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 mbed_slave_obj1000 = 0x12;	/* 18 */
                    subindex mbed_slave_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 mbed_slave_obj1001 = 0x0;	/* 0 */
                    subindex mbed_slave_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 mbed_slave_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t mbed_slave_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex mbed_slave_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 mbed_slave_obj1005 = 0x0;	/* 0 */
                    ODCallback_t mbed_slave_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex mbed_slave_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 mbed_slave_obj1006 = 0x0;	/* 0 */
                    ODCallback_t mbed_slave_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex mbed_slave_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1006 }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 mbed_slave_obj1014 = 0x80;	/* 128 */
                    subindex mbed_slave_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 mbed_slave_highestSubIndex_obj1016 = 0;
                    UNS32 mbed_slave_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 mbed_slave_obj1017 = 1000;
                    ODCallback_t mbed_slave_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex mbed_slave_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 mbed_slave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 mbed_slave_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 mbed_slave_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 mbed_slave_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex mbed_slave_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 mbed_slave_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 mbed_slave_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex mbed_slave_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 mbed_slave_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 mbed_slave_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 mbed_slave_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex mbed_slave_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1400_Event_Timer }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 mbed_slave_highestSubIndex_obj1401 = 5; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 mbed_slave_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 mbed_slave_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1401_Event_Timer = 0x0;	/* 0 */
                    subindex mbed_slave_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1401_Event_Timer }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 mbed_slave_highestSubIndex_obj1402 = 5; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 mbed_slave_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 mbed_slave_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1402_Event_Timer = 0x0;	/* 0 */
                    subindex mbed_slave_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1402_Event_Timer }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 mbed_slave_highestSubIndex_obj1403 = 5; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 mbed_slave_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 mbed_slave_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1403_Event_Timer = 0x0;	/* 0 */
                    subindex mbed_slave_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1403_Event_Timer }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 mbed_slave_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex mbed_slave_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 mbed_slave_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex mbed_slave_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1601[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1601[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1601[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1601[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1601[7] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 mbed_slave_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex mbed_slave_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 mbed_slave_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex mbed_slave_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 mbed_slave_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 mbed_slave_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 mbed_slave_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t mbed_slave_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex mbed_slave_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1800_Event_Timer }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 mbed_slave_highestSubIndex_obj1801 = 5; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 mbed_slave_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 mbed_slave_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1801_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t mbed_slave_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex mbed_slave_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1801_Event_Timer }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 mbed_slave_highestSubIndex_obj1802 = 5; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 mbed_slave_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 mbed_slave_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1802_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t mbed_slave_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex mbed_slave_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1802_Event_Timer }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 mbed_slave_highestSubIndex_obj1803 = 5; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 mbed_slave_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 mbed_slave_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 mbed_slave_obj1803_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t mbed_slave_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex mbed_slave_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&mbed_slave_obj1803_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 mbed_slave_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex mbed_slave_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A00[7] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 mbed_slave_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex mbed_slave_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A01[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A01[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A01[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A01[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 mbed_slave_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex mbed_slave_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 mbed_slave_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 mbed_slave_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex mbed_slave_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&mbed_slave_obj1A03[7] }
                     };

/* index 0x6000 :   Mapped variable Read Inputs 8 Bit */
                    UNS8 mbed_slave_highestSubIndex_obj6000 = 1; /* number of subindex - 1*/
                    subindex mbed_slave_Index6000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj6000 },
                       { RO, uint8, sizeof (UNS8), (void*)&Read_Inputs_8_Bit[0] }
                     };

/* index 0x6002 :   Mapped variable Polarity Input 8 Bit */
                    UNS8 mbed_slave_highestSubIndex_obj6002 = 1; /* number of subindex - 1*/
                    subindex mbed_slave_Index6002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj6002 },
                       { RW, uint8, sizeof (UNS8), (void*)&Polarity_Input_8_Bit[0] }
                     };

/* index 0x6003 :   Mapped variable Filter Constant Input 8 Bit */
                    UNS8 mbed_slave_highestSubIndex_obj6003 = 1; /* number of subindex - 1*/
                    subindex mbed_slave_Index6003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj6003 },
                       { RW, uint8, sizeof (UNS8), (void*)&Filter_Constant_Input_8_Bit[0] }
                     };

/* index 0x6005 :   Mapped variable Global Interrupt Enable Digital */
                    subindex mbed_slave_Index6005[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&Global_Interrupt_Enable_Digital }
                     };

/* index 0x6006 :   Mapped variable Interrupt Mask Any Change 8 Bit */
                    UNS8 mbed_slave_highestSubIndex_obj6006 = 1; /* number of subindex - 1*/
                    subindex mbed_slave_Index6006[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj6006 },
                       { RW, uint8, sizeof (UNS8), (void*)&Interrupt_Mask_Any_Change_8_Bit[0] }
                     };

/* index 0x6007 :   Mapped variable Interrupt Mask Low to High 8 Bit */
                    UNS8 mbed_slave_highestSubIndex_obj6007 = 1; /* number of subindex - 1*/
                    subindex mbed_slave_Index6007[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj6007 },
                       { RW, uint8, sizeof (UNS8), (void*)&Interrupt_Mask_Low_to_High_8_Bit[0] }
                     };

/* index 0x6008 :   Mapped variable Interrupt Mask High to Low 8 Bit */
                    UNS8 mbed_slave_highestSubIndex_obj6008 = 1; /* number of subindex - 1*/
                    subindex mbed_slave_Index6008[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj6008 },
                       { RW, uint8, sizeof (UNS8), (void*)&Interrupt_Mask_High_to_Low_8_Bit[0] }
                     };

/* index 0x6200 :   Mapped variable Write Outputs 8 Bit */
                    UNS8 mbed_slave_highestSubIndex_obj6200 = 1; /* number of subindex - 1*/
                    subindex mbed_slave_Index6200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj6200 },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[0] }
                     };

/* index 0x6202 :   Mapped variable Change Polarity Outputs 8 Bit */
                    UNS8 mbed_slave_highestSubIndex_obj6202 = 1; /* number of subindex - 1*/
                    subindex mbed_slave_Index6202[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj6202 },
                       { RW, uint8, sizeof (UNS8), (void*)&Change_Polarity_Outputs_8_Bit[0] }
                     };

/* index 0x6206 :   Mapped variable Error Mode Outputs 8 Bit */
                    UNS8 mbed_slave_highestSubIndex_obj6206 = 1; /* number of subindex - 1*/
                    subindex mbed_slave_Index6206[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj6206 },
                       { RW, uint8, sizeof (UNS8), (void*)&Error_Mode_Outputs_8_Bit[0] }
                     };

/* index 0x6207 :   Mapped variable Error Value Outputs 8 Bit */
                    UNS8 mbed_slave_highestSubIndex_obj6207 = 1; /* number of subindex - 1*/
                    subindex mbed_slave_Index6207[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&mbed_slave_highestSubIndex_obj6207 },
                       { RW, uint8, sizeof (UNS8), (void*)&Error_Value_Outputs_8_Bit[0] }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable mbed_slave_objdict[] = 
{
  { (subindex*)mbed_slave_Index1000,sizeof(mbed_slave_Index1000)/sizeof(mbed_slave_Index1000[0]), 0x1000},
  { (subindex*)mbed_slave_Index1001,sizeof(mbed_slave_Index1001)/sizeof(mbed_slave_Index1001[0]), 0x1001},
  { (subindex*)mbed_slave_Index1005,sizeof(mbed_slave_Index1005)/sizeof(mbed_slave_Index1005[0]), 0x1005},
  { (subindex*)mbed_slave_Index1006,sizeof(mbed_slave_Index1006)/sizeof(mbed_slave_Index1006[0]), 0x1006},
  { (subindex*)mbed_slave_Index1014,sizeof(mbed_slave_Index1014)/sizeof(mbed_slave_Index1014[0]), 0x1014},
  { (subindex*)mbed_slave_Index1017,sizeof(mbed_slave_Index1017)/sizeof(mbed_slave_Index1017[0]), 0x1017},
  { (subindex*)mbed_slave_Index1018,sizeof(mbed_slave_Index1018)/sizeof(mbed_slave_Index1018[0]), 0x1018},
  { (subindex*)mbed_slave_Index1200,sizeof(mbed_slave_Index1200)/sizeof(mbed_slave_Index1200[0]), 0x1200},
  { (subindex*)mbed_slave_Index1400,sizeof(mbed_slave_Index1400)/sizeof(mbed_slave_Index1400[0]), 0x1400},
  { (subindex*)mbed_slave_Index1401,sizeof(mbed_slave_Index1401)/sizeof(mbed_slave_Index1401[0]), 0x1401},
  { (subindex*)mbed_slave_Index1402,sizeof(mbed_slave_Index1402)/sizeof(mbed_slave_Index1402[0]), 0x1402},
  { (subindex*)mbed_slave_Index1403,sizeof(mbed_slave_Index1403)/sizeof(mbed_slave_Index1403[0]), 0x1403},
  { (subindex*)mbed_slave_Index1600,sizeof(mbed_slave_Index1600)/sizeof(mbed_slave_Index1600[0]), 0x1600},
  { (subindex*)mbed_slave_Index1601,sizeof(mbed_slave_Index1601)/sizeof(mbed_slave_Index1601[0]), 0x1601},
  { (subindex*)mbed_slave_Index1602,sizeof(mbed_slave_Index1602)/sizeof(mbed_slave_Index1602[0]), 0x1602},
  { (subindex*)mbed_slave_Index1603,sizeof(mbed_slave_Index1603)/sizeof(mbed_slave_Index1603[0]), 0x1603},
  { (subindex*)mbed_slave_Index1800,sizeof(mbed_slave_Index1800)/sizeof(mbed_slave_Index1800[0]), 0x1800},
  { (subindex*)mbed_slave_Index1801,sizeof(mbed_slave_Index1801)/sizeof(mbed_slave_Index1801[0]), 0x1801},
  { (subindex*)mbed_slave_Index1802,sizeof(mbed_slave_Index1802)/sizeof(mbed_slave_Index1802[0]), 0x1802},
  { (subindex*)mbed_slave_Index1803,sizeof(mbed_slave_Index1803)/sizeof(mbed_slave_Index1803[0]), 0x1803},
  { (subindex*)mbed_slave_Index1A00,sizeof(mbed_slave_Index1A00)/sizeof(mbed_slave_Index1A00[0]), 0x1A00},
  { (subindex*)mbed_slave_Index1A01,sizeof(mbed_slave_Index1A01)/sizeof(mbed_slave_Index1A01[0]), 0x1A01},
  { (subindex*)mbed_slave_Index1A02,sizeof(mbed_slave_Index1A02)/sizeof(mbed_slave_Index1A02[0]), 0x1A02},
  { (subindex*)mbed_slave_Index1A03,sizeof(mbed_slave_Index1A03)/sizeof(mbed_slave_Index1A03[0]), 0x1A03},
  { (subindex*)mbed_slave_Index6000,sizeof(mbed_slave_Index6000)/sizeof(mbed_slave_Index6000[0]), 0x6000},
  { (subindex*)mbed_slave_Index6002,sizeof(mbed_slave_Index6002)/sizeof(mbed_slave_Index6002[0]), 0x6002},
  { (subindex*)mbed_slave_Index6003,sizeof(mbed_slave_Index6003)/sizeof(mbed_slave_Index6003[0]), 0x6003},
  { (subindex*)mbed_slave_Index6005,sizeof(mbed_slave_Index6005)/sizeof(mbed_slave_Index6005[0]), 0x6005},
  { (subindex*)mbed_slave_Index6006,sizeof(mbed_slave_Index6006)/sizeof(mbed_slave_Index6006[0]), 0x6006},
  { (subindex*)mbed_slave_Index6007,sizeof(mbed_slave_Index6007)/sizeof(mbed_slave_Index6007[0]), 0x6007},
  { (subindex*)mbed_slave_Index6008,sizeof(mbed_slave_Index6008)/sizeof(mbed_slave_Index6008[0]), 0x6008},
  { (subindex*)mbed_slave_Index6200,sizeof(mbed_slave_Index6200)/sizeof(mbed_slave_Index6200[0]), 0x6200},
  { (subindex*)mbed_slave_Index6202,sizeof(mbed_slave_Index6202)/sizeof(mbed_slave_Index6202[0]), 0x6202},
  { (subindex*)mbed_slave_Index6206,sizeof(mbed_slave_Index6206)/sizeof(mbed_slave_Index6206[0]), 0x6206},
  { (subindex*)mbed_slave_Index6207,sizeof(mbed_slave_Index6207)/sizeof(mbed_slave_Index6207[0]), 0x6207},
};

const indextable * mbed_slave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = mbed_slave_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = mbed_slave_Index1006_callbacks; break;
		case 0x1014: i = 4;break;
		case 0x1017: i = 5;*callbacks = mbed_slave_Index1017_callbacks; break;
		case 0x1018: i = 6;break;
		case 0x1200: i = 7;break;
		case 0x1400: i = 8;break;
		case 0x1401: i = 9;break;
		case 0x1402: i = 10;break;
		case 0x1403: i = 11;break;
		case 0x1600: i = 12;break;
		case 0x1601: i = 13;break;
		case 0x1602: i = 14;break;
		case 0x1603: i = 15;break;
		case 0x1800: i = 16;*callbacks = mbed_slave_Index1800_callbacks; break;
		case 0x1801: i = 17;*callbacks = mbed_slave_Index1801_callbacks; break;
		case 0x1802: i = 18;*callbacks = mbed_slave_Index1802_callbacks; break;
		case 0x1803: i = 19;*callbacks = mbed_slave_Index1803_callbacks; break;
		case 0x1A00: i = 20;break;
		case 0x1A01: i = 21;break;
		case 0x1A02: i = 22;break;
		case 0x1A03: i = 23;break;
		case 0x6000: i = 24;break;
		case 0x6002: i = 25;break;
		case 0x6003: i = 26;break;
		case 0x6005: i = 27;break;
		case 0x6006: i = 28;break;
		case 0x6007: i = 29;break;
		case 0x6008: i = 30;break;
		case 0x6200: i = 31;break;
		case 0x6202: i = 32;break;
		case 0x6206: i = 33;break;
		case 0x6207: i = 34;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &mbed_slave_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status mbed_slave_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index mbed_slave_firstIndex = {
  7, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  12, /* PDO_RCV_MAP */
  16, /* PDO_TRS */
  20 /* PDO_TRS_MAP */
};

const quick_index mbed_slave_lastIndex = {
  7, /* SDO_SVR */
  0, /* SDO_CLT */
  11, /* PDO_RCV */
  15, /* PDO_RCV_MAP */
  19, /* PDO_TRS */
  23 /* PDO_TRS_MAP */
};

const UNS16 mbed_slave_ObjdictSize = sizeof(mbed_slave_objdict)/sizeof(mbed_slave_objdict[0]); 

CO_Data mbed_slave_Data = CANOPEN_NODE_DATA_INITIALIZER(mbed_slave);

